### ISSUE TITLE
ALL_FACE contour positions wrong on iOS

### ISSUE THREAD

**Issue by shliama** [brianmtully/flutter_google_ml_vision#14]
Same flutter code, using the same contour indexes (based on [official doc](https://developers.google.com/ml-kit/vision/face-detection/face-detection-concepts#contours)) - iOS clearly has an issue. The code worked fine with the dead `firebase_ml_vision` plugin.

The code below looks okay to me, since it's pretty much the same as on Android. But I guess there is some issue with the contour parts 🤔 order.https://github.com/brianmtully/flutter_google_ml_vision/blob/e8dfedc8335fdd4bde861008cf290df6523f94e9/ios/Classes/FaceDetector.m#L123 

Android | iOS
------------ | -------------
![android](https://user-images.githubusercontent.com/2311626/119298939-b1c38900-bc66-11eb-8c67-efa3365e0d9f.jpeg) | ![ios](https://user-images.githubusercontent.com/2311626/119298956-b7b96a00-bc66-11eb-9b45-f0d87555727a.jpeg)

**Comment by brianmtully** [comment]
Can you provide your drawing function for the contours that you are using?

**Comment by shliama** [comment]
Sure, here is a gist with the CustomPainter and snippet of its usage, should be easy to add into the plugin sample.

https://gist.github.com/shliama/f1ae6add1c879a0b0404e91fc1ae2f39

**Comment by brianmtully** [comment]
So after further inspection, the contours array returned on iOS are not in the order that you are expecting. The iOS MLKit doesn't seem to follow the order from the documentation when I grab all of the contours of a face. In order to get the result you expect I probably have to go one by one and input them into the resulting array. 

allPoints isn't actually a contourType if you look through the documentation. I am just pulling all the points by looping through all the actual contours.

**Comment by shliama** [comment]
Changed the code based on your idea - https://github.com/brianmtully/flutter_google_ml_vision/pull/16
Tested with my mask and everything looks perfectly aligned now between iOS & Android.

**Comment by brianmtully** [comment]
thank you, I merged your pull request.
